# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya'
  pod 'Moya-ObjectMapper'
  pod 'RealmSwift'
  pod "VK-ios-sdk" 
  pod "Haptica" 

  


end
